version: '3.1'

services:

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - 3306:3306
    networks: 
      yuanxin:
    environment:
      # MYSQL_ROOT_PASSWORD: OC#oc2018
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    volumes:
     - ./db/mysql/data:/var/lib/mysql
     - ./db/mysql/log:/var/log/mysql
     - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
     - ./init.d/:/docker-entrypoint-initdb.d/:ro

  api:
    image: daocloud.io/dfang/yuanxin_api
    container_name: api
    restart: always
    environment:
      APP_DB_USER: root
      APP_DB_PASSWORD:
      APP_DB_HOST: tcp(db:3306)
      APP_DB_NAME: news
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
    networks: 
      yuanxin:
    links:
      - db:db
    ports:
      - 9090:9090
  
  admin:
    image: daocloud.io/dfang/yuanxin_admin
    # build:
    #   context: ../yuanxin_admin
    container_name: admin
    restart: always
    networks: 
      yuanxin:
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 3000:3000
    environment:
      RAILS_MASTER_KEY: 609ced37432b8493776e9969bd0dae25
      DATABASE_URL: mysql2://root:@db/news

  elasticsearch:
    image: elasticsearch
    networks: 
      yuanxin:
    ports:
      - 9200:9200
      - 9300:9300

  gme:
    image: dfang/go-mysql-elasticsearch
    links:
      - elasticsearch:es
    restart: always
    networks: 
      yuanxin:
    depends_on:
      - db
      - elasticsearch
    volumes:
      # - ./config/river.toml:/go/src/github.com/siddontang/go-mysql-elasticsearch/river/etc/river.toml
      - ./config/river.toml:/go/etc/river.toml

  # kibana:
  #   image: kibana
  #   ports:
  #     - 5601:5601
  redis:
    image: redis
    networks: 
      yuanxin:
    ports:
      - 6379:6379
  
  worker:
    image: daocloud.io/dfang/yuanxin_worker
    depends_on:
      - db
      - redis
    networks: 
      yuanxin:
    environment:
      APP_DB_USER: root
      APP_DB_PASSWORD:
      APP_DB_HOST: tcp(db:3306)
      APP_DB_NAME: news
      REDIS_HOST: redis
      REDIS_PORT: 6379

networks: 
  yuanxin:
